name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Altere para o nome da sua branch principal, se for diferente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.100

      - name: Build and publish
        run: dotnet publish -c Release -o
        working-directory: Pages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: /Pages/Index.cstml
